apiVersion: v1
kind: Pod
metadata:
  name: osrs_ge-api
  labels:
    app: osrs_ge-api
spec:
  containers:
    - name: api
      image: ghcr.io/fisherrjd/osrs_ge-api:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
          hostPort: 8000
      env:
        - name: DB_FILE
          value: 'sqlite:////data/item_data.db'
      volumeMounts:
        - name: db-storage
          mountPath: /data

    - name: data-fetcher
      image: ghcr.io/fisherrjd/osrs_ge-fetcher:latest
      imagePullPolicy: Always
      env:
        - name: DB_FILE
          value: 'sqlite:////data/item_data.db'
      volumeMounts:
        - name: db-storage
          mountPath: /data

    - name: news-fetcher
      image: ghcr.io/fisherrjd/osrs_ge-news:latest
      imagePullPolicy: Always
      env:
        - name: DB_FILE
          value: 'sqlite:////data/news.db'
      volumeMounts:
        - name: db-storage
          mountPath: /data

  volumes:
    - name: db-storage
      hostPath:
        path: /var/lib/osrs-ge/data
        type: Directory
